str4d/rage

- src/bin/rage/main.rs
- src/cli_common.rs
- src/keys.rs
- src/lib.rs
- src/openssh.rs
- src/protocol.rs
We parse them in order to detect them, and then immediately reject them as unsupported, with a helpful message to inform users how to migrate away.
> Encrypted PEM keys

- src/format.rs
- src/protocol.rs
The armored header was being incorrectly serialized for MAC calculation using the binary magic instead of the armored magic.
> Fix MAC calculation for armored headers

- Cargo.lock
- Cargo.toml
- src/error.rs
- src/format.rs
- src/format/scrypt.rs
- src/keys.rs
- src/primitives.rs
- src/primitives/stream.rs
- src/protocol.rs
- `Cargo.toml` is now annotated with the purpose of every dependency in the library.
- Some unnecessary direct dependencies have been dropped.
Kudos to [dochtman](https://www.reddit.com/r/rust/comments/egn81r/rage_a_simple_secure_and_modern_encryption_tool/fc80el0/) for the comments that prompted this refactor.
> Reorganise dependencies

- src/bin/rage-mount/main.rs
- src/bin/rage/error.rs
- src/bin/rage/main.rs
- src/cli_common.rs
If a user does not specify -i/--identity and the default identities file
does not exist, the user is now informed about it.
Closes #39.
> Re-enable the default identities file

- .github/workflows/interop.yml
- CHANGELOG.md
- src/bin/rage-keygen/main.rs
- src/bin/rage/main.rs
- src/cli_common/file_io.rs
> File I/O tweaks

- CHANGELOG.md
- src/format.rs
- src/format/plugin.rs
- src/format/ssh_rsa.rs
- src/util.rs
This ensures that unknown recipient lines are ignored during decryption,
rather than causing a hard decryption failure.
Closes #36.
> Parse and serialize unknown recipient lines

- Cargo.lock
- Cargo.toml
- benches/throughput.rs
The performance improvement comes from the upgraded `chacha20` dependency. Performance is slightly improved by default, and compiling with `RUSTFLAGS="-Ctarget-feature=+avx2"` will boost performance significantly.
Part of #57.
> Performance improvements

- age/CHANGELOG.md
- age/src/cli_common.rs
- age/src/keys.rs
- age/src/lib.rs
- age/src/protocol.rs
- rage/src/bin/rage-mount/main.rs
- rage/src/bin/rage/main.rs
Passphrase decryption (which fetches a passphrase ahead of time) no longer requires a no-op closure, and similarly identity decryption can be implemented without support for encrypted identities. It is also easier to modify the Callbacks trait if we find other callbacks that are necessary.
> Replace read_passphrase closure with Callbacks trait

- Cargo.lock
- age/CHANGELOG.md
- age/Cargo.toml
- age/src/cli_common.rs
- rage/CHANGELOG.md
- rage/Cargo.toml
- rage/src/bin/rage-mount/main.rs
- rage/src/bin/rage/error.rs
- rage/src/bin/rage/main.rs
> Use pinentry for passphrase input if available

- Cargo.lock
- Cargo.toml
- age-core/Cargo.toml
- age-core/README.md
- age-core/src/format.rs
- age-core/src/lib.rs
- age/CHANGELOG.md
- age/Cargo.toml
- age/src/format.rs
- age/src/format/plugin.rs
- age/src/format/scrypt.rs
- age/src/format/ssh_ed25519.rs
- age/src/format/ssh_rsa.rs
- age/src/format/x25519.rs
- age/src/util.rs
`age-core` will be the home for low-level age components that will be reused by e.g. the plugin system (plugins themselves will not need the entire `age` crate).
Other changes in this PR:
- Serialization of age stanzas has been refactored to use a common format function.
- The age stanza parser is now significantly simpler.
- Stanzas with empty bodies are correctly parsed.
Part of #45.
> Move age stanza parsing and serialization to new age-core crate

- age/CHANGELOG.md
- age/src/format.rs
- age/src/format/plugin.rs
- age/src/protocol.rs
Keeps the joint well oiled!
Oil is not added during passphrase encryption, because an scrypt recipient SHOULD be the only recipient.
> Insert a random recipient stanza into the header during encryption

- Cargo.lock
- age/Cargo.toml
- age/src/primitives/stream.rs
Improves encryption throughput by around 60% over standard, and around 10% when compiled with the AVX2 flag, because c2-chacha uses AVX2 when available.
Part of #57.
> Switch to c2-chacha crate for ChaCha20-IETF

- Cargo.lock
- age/Cargo.toml
- age/src/primitives.rs
This removes the `chacha20` crate from our dependency tree.
> Replace chacha20 with c2-chacha in all primitives

- age/CHANGELOG.md
- age/src/primitives/armor.rs
- age/src/primitives/stream.rs
- age/src/protocol.rs
- rage/CHANGELOG.md
- rage/src/bin/rage-mount/main.rs
This along with some other refactors enables us to handle seekable and non-seekable readers with a single API.
> impl Seek for ArmoredReader

- age/CHANGELOG.md
- age/src/error.rs
- age/src/lib.rs
- age/src/protocol.rs
- age/src/protocol/decryptor.rs
- rage/CHANGELOG.md
- rage/examples/generate-completions.rs
- rage/examples/generate-docs.rs
- rage/src/bin/rage-mount/main.rs
- rage/src/bin/rage/error.rs
- rage/src/bin/rage/main.rs
The decryption workflow has been inverted: the file header is parsed to detect the decryption type, and this is then represented as an enum of concrete decryptors with context-specific `decrypt()` methods.
The `-p/--passphrase` flag has been removed from rage-mount, and is now not required for decryption with rage.
Closes #83.
> Refactor age::Decryptor to auto-detect decryption type

- rage/src/bin/rage/error.rs
- rage/src/bin/rage/main.rs
If a user tries to pipe to a program that is not reading from stdin (or
stops doing so early), the default Rust error is something like:
Broken pipe (os error 32)
which is pretty opaque. While there might be other possible causes for
this error, we handle the most likely cause by wrapping this with a
custom error that suggests the user check whether the output is being
read. For example, this command would trigger the error:
rage -p -a file.txt | cat foo
while this would not:
rage -p -a file.txt | cat -
Closes str4d/rage#54.
> Give a more useful error when encryption fails with BrokenPipe

- Cargo.lock
- age/CHANGELOG.md
- age/Cargo.toml
- age/src/openssh.rs
When OpenSSH introduced its current encrypted-key format, ssh-keygen
defaulted to "aes256-cbc" for the cipher. This was changed in OpenSSH 7.6
(released 2017-10-03) to "aes256-ctr", and is the same to this day.
Adding support for "aes256-cbc" ensures compatibility with all encrypted
keys generated by ssh-keygen in this format since it was introduced in
OpenSSH 6.5 (released 2014-01-30).
See also https://github.com/FiloSottile/age/issues/100
> Add support for OpenSSH keys encrypted with "aes256-cbc"

- Cargo.lock
- age-core/CHANGELOG.md
- age-core/Cargo.toml
- age-core/src/lib.rs
- age-core/src/primitives.rs
- age/src/format/scrypt.rs
- age/src/format/ssh_ed25519.rs
- age/src/format/x25519.rs
- age/src/primitives.rs
- age/src/primitives/stream.rs
- age/src/protocol.rs
This enables reuse of these common primitives within the upcoming plugin
system, alongside the core parsers and serializers.
> age_core: Expose primitives for AEAD and HKDF

- .github/workflows/interop.yml
This enables the age developers to proactively detect when they make changes that cause an interoperability failure, rather than relying on the rage developers to notify them manually.
> CI: Enable interoperability tests to be triggered by age commits

- age/CHANGELOG.md
- age/src/cli_common.rs
- age/src/format.rs
- age/src/format/plugin.rs
- age/src/format/scrypt.rs
- age/src/format/ssh_ed25519.rs
- age/src/format/ssh_rsa.rs
- age/src/format/x25519.rs
- age/src/identity.rs
- age/src/keys.rs
- age/src/lib.rs
- age/src/protocol.rs
- age/src/protocol/decryptor.rs
- age/src/ssh/identity.rs
- rage/src/bin/rage-mount/main.rs
- rage/src/bin/rage/main.rs
This decouples the identity implementations from the age library, enabling external implementations of identities (leveraging the flexibility of the age format's single joint).
Part of #99.
> Introduce an Identity trait

- Cargo.lock
- age-core/CHANGELOG.md
- age-core/Cargo.toml
- age-core/src/format.rs
- age-core/src/lib.rs
- age/CHANGELOG.md
- age/src/format.rs
- age/src/identity.rs
- age/src/keys.rs
- age/src/lib.rs
- age/src/protocol.rs
- age/src/protocol/decryptor.rs
- age/src/scrypt.rs
- age/src/ssh/identity.rs
- age/src/ssh/recipient.rs
- age/src/x25519.rs
`Stanza` and `FileKey` are in the public API for implementations, but are unnecessary for users.
> Move more core structs into age-core

- age/benches/throughput.rs
- age/src/x25519.rs
- Add Decryptor benchmarks.
- Include the header-handling time within the benchmarks.
> age: Rework throughput benchmarks

- Cargo.lock
- age/CHANGELOG.md
- age/Cargo.toml
- age/src/cli_common.rs
- rage/CHANGELOG.md
- rage/examples/generate-docs.rs
- rage/i18n/en-US/rage.ftl
- rage/i18n/es-AR/rage.ftl
- rage/i18n/it-IT/rage.ftl
- rage/i18n/zh-CN/rage.ftl
- rage/i18n/zh-TW/rage.ftl
- rage/src/bin/rage-mount/main.rs
- rage/src/bin/rage/error.rs
- rage/src/bin/rage/main.rs
Instead of configuring defaults, users should specify identity files directly.
> Remove support for a default identity (or alias) path

- age/src/error.rs
Thanks for the recent release!
This makes EncryptError slightly easier to use with anyhow and
other libraries that leverage `std::error::Error`.
> feat(error): implement std error for EncryptError

- rage/CHANGELOG.md
- rage/src/bin/rage-keygen/main.rs
- rage/src/bin/rage-mount/main.rs
- rage/src/bin/rage/main.rs
Log output can be enabled with the `RUST_LOG` environment variable.
Closes str4d/rage#156
> rage: Disable log output by default

- Cargo.lock
- Cargo.toml
- age-core/Cargo.toml
- age-core/src/lib.rs
- age-core/src/plugin.rs
- age-plugin/Cargo.toml
- age-plugin/README.md
- age-plugin/examples/age-plugin-unencrypted.rs
- age-plugin/src/identity.rs
- age-plugin/src/lib.rs
- age-plugin/src/recipient.rs
- age/Cargo.toml
- age/i18n/en-US/age.ftl
- age/src/cli_common.rs
- age/src/error.rs
- age/src/identity.rs
- age/src/lib.rs
- age/src/plugin.rs
- age/src/protocol/decryptor.rs
- rage/Cargo.toml
- rage/src/bin/rage/error.rs
- rage/src/bin/rage/main.rs
https://hackmd.io/@str4d/age-plugin-spec
Plugin functionality is being merged behind the `unstable` feature flag, so expect that it might be adjusted in subsequent releases while we figure out the gaps.
> Plugin interface

- age/src/ssh.rs
- age/src/ssh/recipient.rs
Instead of hard-coding the list, we rely on the invariant that all SSH
pubkeys have the form `key_type Base64(string(key_type) || ...)`.
> age: Ignore all unsupported SSH pubkey types

- age/CHANGELOG.md
- age/src/cli_common/file_io.rs
- rage/CHANGELOG.md
This avoids rage leaving behind an empty file when an error occurs before
we write the header.
> age: Open files lazily in age::cli_common::file_io::OutputWriter

- age/src/cli_common/file_io.rs
Otherwise, `rage` fails with:
```bash 
$ echo | rage -r age100qf7fggvctqclsqvl2xu6vjnrerxm9vt8x56yql6gaz9x54vcaqdh2q26 -o existing-file.age
Error: File exists (os error 17)
```
> Allow overwriting existing output file

- rage/i18n/en-US/rage.ftl
- rage/src/bin/rage/error.rs
- rage/src/bin/rage/main.rs
Now that we are going to overwrite OUTPUT instead of halting with "file exists", we do not want it to be set to INPUT!
> rage: Prevent INPUT and OUTPUT from being set to the same path

- age-core/CHANGELOG.md
- age-core/src/plugin.rs
- age-plugin/examples/age-plugin-unencrypted.rs
- age-plugin/src/identity.rs
- age-plugin/src/lib.rs
- age-plugin/src/recipient.rs
- age/CHANGELOG.md
- age/src/cli_common.rs
- age/src/lib.rs
- age/src/plugin.rs
- age/src/protocol/decryptor.rs
- age/src/ssh/identity.rs
- rage/src/bin/rage/main.rs
This brings in the last changes to the plugin specification:
- Phase 2 of the `recipient-v1` state machine is now bi-directional, enabling plugins to interact with users during encryption.
- Plugins may receive identities as well as recipients during the `recipient-v1` state machine.
- Plugins can now request non-secret strings from users, in addition to secret strings like passphrases. User input will not be hidden int the UI when requesting non-secret strings.
> Plugin protocol updates

- README.md
- age/src/ssh/recipient.rs
- rage/CHANGELOG.md
- rage/examples/generate-completions.rs
- rage/examples/generate-docs.rs
- rage/i18n/en-US/rage.ftl
- rage/i18n/es-AR/rage.ftl
- rage/i18n/it-IT/rage.ftl
- rage/i18n/zh-CN/rage.ftl
- rage/i18n/zh-TW/rage.ftl
- rage/src/bin/rage/error.rs
- rage/src/bin/rage/main.rs
This is specifically intended to support plugins that use symmetric identities, where both encryption and decryption require a secret. We don't want recipient strings (`age1name1...`) to contain secret values, as this is easily overlooked by users. Instead, symmetric plugins would only provide an identity file, and users would provide it during both encryption and decryption.
As a side-effect, we now also support using identity files for native age recipients and asymmetric plugins, as well as SSH keys; this keeps the UX consistent.
To prevent ambiguity (e.g. if the user wants to decrypt but forgets the `-d/--decrypt` flag), we add an `-e/--encrypt` flag and require it when encrypting to identity files.
> rage: Allow encrypting to identity files

- Cargo.lock
- age-core/Cargo.toml
- age-core/src/plugin.rs
We don't want plugin binaries to make any assumptions about where they are run from. The easiest way to ensure this is to always run them from a fresh temporary directory.
Closes str4d/rage#200.
> age-core: Start plugin binaries in a temporary working directory

- age/Cargo.toml
This instructs docs.rs to render the feature-flagged parts of the library
in the documentation.
Fixes str4d/rage#209.
> age: Enable all features and doc_cfg for docs.rs

- HomebrewFormula/rage.rb
Just a small update here, bumping the Homebrew formula to the 0.5.1 release. Thanks for the work on Rage! 🙂
> Update Homebrew formula to 0.5.1

- .github/workflows/release.yml
This ensures they are linked to earlier versions of `libc` and `libpcsclite`.
Debian packages are built with Ubuntu 18.04 as this is required for `cargo-deb`.
> CI: Build Linux releases with earlier Ubuntu versions

- rage/i18n/en-US/rage.ftl
- rage/i18n/es-AR/rage.ftl
- rage/i18n/it-IT/rage.ftl
- rage/i18n/zh-CN/rage.ftl
- rage/i18n/zh-TW/rage.ftl
- rage/src/bin/rage-keygen/main.rs
- rage/src/bin/rage-mount/main.rs
- rage/src/bin/rage/main.rs
`i18n-embed-fl` doesn't correctly handle indentation whitespace preceding a variable. By using explicit string syntax for whitespace, we avoid this issue by not having any implicit indentations.
> rage: Use explicit syntax for indentation whitespace

- Cargo.lock
- age-core/Cargo.toml
- age/Cargo.toml
- age/src/primitives.rs
- fuzz-afl/Cargo.lock
- fuzz/Cargo.lock
Excludes:
- `aes 0.7` (requires MSRV bump to 1.49, and `aes-ctr` has not upgraded its trait dependency yet).
- `chacha20poly1305 0.8` (`c2-chacha` has not upgraded its trait dependency yet).
- `rand 0.8` (we depend on crates that require `0.7`).
> Dependency updates for 0.6.0

- README.md
- age/README.md
- age/src/lib.rs
This is a common point of confusion in the community, but the proper name of the language is simply "Go". See https://golang.org/doc/faq#go_or_golang.
Thanks for all your work!
> *: use Go rather than Golang

- age-core/CHANGELOG.md
- age-core/src/format.rs
- age-core/src/lib.rs
- age/src/format.rs
Single-stanza headers now take around 55% less time to parse, while multi-header stanzas (benchmarked up to 9) take around 60-70% less time to parse.
This translates to a 25-30% reduction in decryption time for small (<16kB) age files, down to around 5% for 1MB files.
> Header decoding performance improvements

- Cargo.lock
- age-core/CHANGELOG.md
- age-core/Cargo.toml
- age-core/src/format.rs
- age-plugin/CHANGELOG.md
- age-plugin/Cargo.toml
- age/CHANGELOG.md
- age/Cargo.toml
- fuzz-afl/Cargo.lock
- fuzz/Cargo.lock
- fuzz/fuzz_targets/age_stanza.rs
- fuzz/fuzz_targets/decrypt.rs
- rage/CHANGELOG.md
- rage/Cargo.toml
In 0.7.0, Base64 decoding was moved to the `AgeStanza::body` method, with the stanza parser only checking for valid Base64 characters. This caused the parser to start accepting stanzas with non-canonical last body lines (where the Base64 encoding would have trailing bits that could not be decoded into full bytes); calling `AgeStanza::body` on these stanzas would cause a panic.
We fix the parser to reject non-canonical last body lines, turning the panic back into an error.
> Fix panic in `AgeStanza::body`

- Cargo.lock
- age-core/Cargo.toml
- age/Cargo.toml
- age/src/error.rs
- age/src/format.rs
- age/src/primitives.rs
- age/src/ssh/identity.rs
- age/src/ssh/recipient.rs
- fuzz-afl/Cargo.lock
- fuzz/Cargo.lock
We need to depend on two versions of the `sha2` crate because `rsa` doesn't have a version depending on `digest 0.10` yet.
> Migrate to hkdf 0.12

- Cargo.lock
- age-core/CHANGELOG.md
- age-core/Cargo.toml
- age-core/src/io.rs
- age-core/src/lib.rs
- age-core/src/plugin.rs
- age-plugin/examples/age-plugin-unencrypted.rs
- age/src/plugin.rs
- fuzz-afl/Cargo.lock
- fuzz/Cargo.lock
Setting the `AGEDEBUG` environment variable to `plugin` will cause all
plugin communications, as well as the plugin's stderr, to be printed to
the stderr of the parent process (e.g. rage).
> Add helper environment variable for debugging plugins

- age/src/cli_common.rs
- age/src/encrypted.rs
- age/tests/test_vectors.rs
Some places in the code rely on features without conditional compilation for that code. This causes compiler errors for some combinations of features. 
For example, having the `cli-common` feature enabled but not the `plugin` feature resulted in a compiler error because `IdentityFileEntry::into_identity` could return a `ReadError::MissingPlugin`, which is disabled when the `plugin` feature is disabled.
These commits address a few of these cases where compiler errors are emitted. The patched version passes the tests for all members of the power set of the features `["armor", "async", "cli-common", "plugin", "ssh"]`. This was tested using
[https://github.com/frewsxcv/cargo-all-features](https://github.com/frewsxcv/cargo-all-features).
This only resolves compiler errors, but if this was …
> Resolve compiler errors for incompatible feature combinations

- rage/i18n/en-US/rage.ftl
- rage/src/bin/rage/error.rs
- rage/src/bin/rage/main.rs
This matches the detection done by `age`.
Closes str4d/rage#287.
> rage: Detect PowerShell corruption during decryption

- age/CHANGELOG.md
- age/src/primitives/stream.rs
In str4d/rage#319 we required the last STREAM chunk to be non-empty, as this is generally non-canonical (and can be represented instead by the chunk marked as last being full). The sole exception to this is if the plaintext has length zero, in which case there is no "previous" chunk, and the single empty chunk is the canonical representation.
There generally isn't a good reason to create empty age ciphertexts, as most identities don't provide authentication guarantees, but we've allowed them in the past.
> age: Allow ciphertexts that encrypt the empty plaintext

- age/src/ssh.rs
- age/src/ssh/identity.rs
This makes SSH identities cloneable, which is consistent with age identities.
No functional changes otherwise.
> age/ssh: make `ssh::Identity: Clone`

- age/Cargo.toml
- age/benches/throughput.rs
`cargo test` currently fails on Apple M1 processors with this error:
```
Compiling i18n-embed v0.13.4
Compiling i18n-embed-fl v0.6.4
Compiling criterion-cycles-per-byte v0.1.2
error: criterion-cycles-per-byte currently relies on x86 or x86_64.
--> /Users/macil/.cargo/registry/src/github.com-1ecc6299db9ec823/criterion-cycles-per-byte-0.1.2/src/lib.rs:34:1
|
34 | compile_error!("criterion-cycles-per-byte currently relies on x86 or x86_64.");
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
error[E0308]: mismatched types
--> /Users/macil/.cargo/registry/src/github.com-1ecc6299db9ec823/criterion-cycles-per-byte-0.1.2/src/lib.rs:41:15
|
41 | fn rdtsc() -> u64 {
|    -----      ^^^ expected `u64`, found `()`
|    |
|    implicitly returns `()` as its body has no …
```
> Fix test and bench support for ARM CPUs

- age/benches/throughput.rs
Follow-up to https://github.com/str4d/rage/pull/322. This PR removes a call to `.with_measurement(CyclesPerByte)` which was merely redundant on x86/64 systems, but would cause a compile error on non-Unix non-x86/64 systems. (Non-x86/64 test runs were already broken prior to #322 so it wasn't a regression.)
Related comment: https://github.com/str4d/rage/pull/322/files#r912559075
> Fix tests on non-unix non-x86/64

- HomebrewFormula/rage.rb
Homebrew has methods to pass common arguments for several languages' build systems. You can find examples by searching for packaged rust software in [homebrew core](https://github.com/Homebrew/homebrew-core/tree/master/Formula). Diesel, rg, and procs are good examples.
> Use homebrew's rust install stanza

- Cargo.lock
- rage/Cargo.toml
- rage/src/bin/rage-mount/main.rs
- rage/src/bin/rage-mount/tar.rs
- rage/src/bin/rage-mount/zip.rs
I picked the first commit of `fuse_mt` that switched from using `fuse` to `fuser` (`fuse_mt` hasn't had any new releases since 0.5.1). That way `rage-mount` can be built against libfuse3. `time` and `zip` dependencies update is a side effect due to TimeSpec being obsolete.
WARNING: I've never written any Rust code before, so please bear with my ignorance in the PR.
> rage-mount: update dependencies fuse_mt, time and zip

- Cargo.lock
- age-core/Cargo.toml
- age-core/src/primitives.rs
- age-plugin/Cargo.toml
- age/Cargo.toml
- age/src/primitives/stream.rs
- age/src/ssh/identity.rs
- age/src/ssh/recipient.rs
- rage/Cargo.toml
This brings us onto Rust Crypto crates with MSRV 1.56 or lower.
Closes #304.
> Migrate to rsa 0.6 and chacha20poly1305 0.10

- Cargo.lock
- age-plugin/Cargo.toml
- age/Cargo.toml
- fuzz-afl/Cargo.lock
- fuzz/Cargo.lock
This upgrades all dependencies to their latest versions, other than those that drop 1.56.0 compatibility (which we are retaining for 0.9.0).
> Update dependencies for rage 0.9.0

- age-core/CHANGELOG.md
- age/CHANGELOG.md
- age/benches/parser.rs
- age/benches/throughput.rs
- age/src/lib.rs
- age/src/protocol.rs
- rage/CHANGELOG.md
- rage/src/bin/rage/main.rs
This removes the ability to encrypt a file to no recipients, which serves no useful purpose.
`rage` already required that recipient arguments be provided, but now it additionally requires that provided recipient files are not empty.
Closes str4d/rage#330.
> Prevent `age::Encryptor` from being constructed with no recipients

- age/src/protocol.rs
By adding the Send trait as a requirement to the recipients vec, we gain the Send trait on Encryptor. This is useful for other async frameworks that require Send across await's.
> Ensure Encryptor implements trait Send

- Cargo.lock
- age/CHANGELOG.md
- age/Cargo.toml
- age/src/ssh.rs
- age/src/ssh/identity.rs
> ssh: Support `aes256-gcm@openssh.com` ciphers for encrypted keys

- age/src/lib.rs
Sorry for such a minor change, but it is the first line of the documentation and I couldn't help seeing it.
> Correct spelling in documentation

- age/src/primitives/stream.rs
`*::io::copy()` return a `WriteZero` error if `poll_write()` returns 0. This change ensures that never happens (assuming the input buffer is not empty), and adds tests using `futures::io::copy()` for that case. The new `stream_async_io_copy_long` test fails without this change.
> StreamWriter AsyncWrite: fix usage with futures::io::copy() and tokio::io::copy()

- age/src/cli_common.rs
- age/src/scrypt.rs
- age/src/ssh/identity.rs
- age/src/ssh/recipient.rs
- age/src/x25519.rs
There's a few places within the codebase where vectors are declared, but not initialized with any capacity, ie `let a = vec![]`. When one knows in advance with reasonable certainty the size of the data that the vector will hold, initializing the vector with that size as the capacity can potentially save on allocations.
For example consider this line without the pre-initialization
```rust
// vector initialized without capacity
let mut salt = vec![];
// memory is allocated for 32 bytes and then the the bytes of `epk` pushed onto the vec
// total memory allocated: 32 bytes
salt.extend_from_slice(epk.as_bytes()); 
// to avoid excessive allocations, rust will allocate twice the capacity (64 bytes)
// total memory allocated: 96 bytes
salt.extend_from_slice(pk.as_bytes());
// total memory …
```
> Initialize Vector With Capacity When Known

- age/CHANGELOG.md
- age/src/format.rs
- age/src/primitives/armor.rs
- age/src/protocol.rs
- age/tests/testkit.rs
> Enable header parsing to use `R: futures::io::AsyncBufRead`

- age/CHANGELOG.md
- age/src/cli_common.rs
`read_line_initial_text` fills the tty input with the initial text. This implies that the returned input is usually prefixed with the initial text, or that the initial text can be removed.
This differs from `age` behaviour, which is to not allow the initial text to be removed.
As a consequence, plugin leveraging callbacks for reading public input (confirm, request_public_string) exhibit a different behaviour depending on if they are called with `age` or `rage`.
This commit replaces `read_line_initial_text` with `write_str` and `read_line`. The initial text is still displayed to the user, but it does not affect the returned output.
> age: Replace callback input `read_line_initial_text` with `write_str` and `read_line`

- age/CHANGELOG.md
- age/src/ssh.rs
- age/src/ssh/recipient.rs
- rage/CHANGELOG.md
- rage/i18n/en-US/rage.ftl
- rage/src/bin/rage/error.rs
- rage/src/bin/rage/main.rs
Also fixes a `rage` bug where OpenSSH private keys containing invalid public keys (but otherwise valid) were being ignored during encryption instead of causing an error.
> Improve errors and changelogs for larger RSA keys

- age/CHANGELOG.md
- age/src/scrypt.rs
> scrypt: Increase `log_n` until it is measurable

- age/CHANGELOG.md
- age/src/x25519.rs
Background motivation is that I'm working on a SOPS in rust project that where I need `Debug` and `PartialEq` implementations for proper and somewhat generic unit testing 😊
> Implement `Debug, PartialEq, Eq`  for `age::x25519::Recipient`.

- age/CHANGELOG.md
- age/src/x25519.rs
Need to store them in a collection that ensures uniqueness :)
> Derive `Hash` for `Recipient`.

- age/i18n/en-US/age.ftl
- age/src/plugin.rs
This enables us to provide a more useful error message when a plugin unexpectedly dies.
Closes str4d/rage#167.
> age: Wrap connections in a blast furnace

- rage/i18n/en-US/rage.ftl
- rage/src/bin/rage/error.rs
- rage/src/bin/rage/main.rs
- rage/tests/cmd/rage/encrypt-missing-recipients-file.toml
This also fixes a test failure on Windows, which had a different OS error message than Unix for "file not found".
> rage: Give a better error message when a recipients file is missing

- README.md
> Add package naming guidance to README

- Cargo.lock
`ahash 0.8.7` is documented as having an MSRV of 1.60, but that release stopped enabling the `stdsimd` feature, as it was only used for AArch64 APIs and that usage was stabilised in 1.72. This broke compilation on Apple ARM devices.
> Downgrade to `ahash 0.8.6`

- rage/tests/cmd/rage-keygen/help_it.toml
- rage/tests/cmd/rage-mount/help_it.toml
- rage/tests/cmd/rage/help_it.toml
`LANG` can be overridden within `DesktopLanguageRequester`, while `LC_ALL` is treated as a universal override. My hypothesis is that macOS is setting some of the override variables, causing `LANG` to be ignored.
> rage: Use `LC_ALL` in CLI tests

- .github/workflows/interop.yml
- age/src/cli_common.rs
- age/src/primitives/armor.rs
This enables identities to be passed via named pipes, because we are no longer opening the file more than once.
Closes str4d/rage#379.
> age: Parse identity files in a single pass

- rage/build.rs
This will make subsequent installation via Homebrew formula easier.
> rage: Use `mount` feature flag to avoid generating `rage-mount` files

- README.md
A [FreeBSD port](https://github.com/freebsd/freebsd-ports/commit/9527b2227431febc7700075a76935159bd1e3b8f) is now available.
Add packaging information for FreeBSD.
> Add informations for FreeBSD

- rage/src/bin/rage-keygen/main.rs
- rage/src/bin/rage-mount/main.rs
- rage/src/bin/rage/main.rs
This ensures that if we have a matching locale for `age` but not `rage`, we don't ignore the `age` locale, and instead use the best match for each of them.
> rage: Revert to using requested langauges for `age` localization

- age-plugin/CHANGELOG.md
- age-plugin/examples/age-plugin-unencrypted.rs
- age-plugin/src/identity.rs
- age-plugin/src/lib.rs
- age-plugin/src/recipient.rs
> age-plugin: Fix `run_state_machine` to enable recipient-only or identity-only plugins

- age-core/CHANGELOG.md
- age-core/src/format.rs
- age-core/src/plugin.rs
- age-plugin/CHANGELOG.md
- age-plugin/examples/age-plugin-unencrypted.rs
- age-plugin/src/identity.rs
- age-plugin/src/lib.rs
- age-plugin/src/recipient.rs
- age/CHANGELOG.md
- age/i18n/en-US/age.ftl
- age/src/encrypted.rs
- age/src/error.rs
- age/src/lib.rs
- age/src/plugin.rs
- age/src/protocol.rs
- age/src/scrypt.rs
- age/src/ssh/identity.rs
- age/src/ssh/recipient.rs
- age/src/x25519.rs
> Implement labels

- age/src/cli_common/error.rs
- age/src/cli_common/identities.rs
- age/src/cli_common/recipients.rs
> age: Fix feature flag combination bugs in `cli_common` module

- age/src/protocol.rs
- age/src/scrypt.rs
This can only be configured by using `scrypt::Recipient` directly in a library context. The helper method `Encryptor::with_user_passphrase` does not expose this, and `rage` continues to use the default.
Closes str4d/rage#383.
> age: Add `scrypt::Recipient::set_work_factor` for overriding default

- rage/src/bin/rage-keygen/cli.rs
- rage/src/bin/rage-mount/cli.rs
- rage/src/bin/rage/cli.rs
Fixes https://github.com/str4d/rage/issues/512
> Better completions

- age/CHANGELOG.md
- age/benches/parser.rs
- age/benches/throughput.rs
- age/i18n/en-US/age.ftl
- age/i18n/es-AR/age.ftl
- age/i18n/fr/age.ftl
- age/i18n/it/age.ftl
- age/i18n/ru/age.ftl
- age/i18n/zh-CN/age.ftl
- age/i18n/zh-TW/age.ftl
- age/src/error.rs
- age/src/lib.rs
- age/src/primitives/armor.rs
- age/src/protocol.rs
- rage/i18n/en-US/rage.ftl
- rage/i18n/es-AR/rage.ftl
- rage/i18n/fr/rage.ftl
- rage/i18n/it/rage.ftl
- rage/i18n/ru/rage.ftl
- rage/i18n/zh-CN/rage.ftl
- rage/i18n/zh-TW/rage.ftl
- rage/src/bin/rage/error.rs
- rage/src/bin/rage/main.rs
This aligns it with `Decryptor`, and means that recipients can be used to encrypt multiple files without cloning.
Part of str4d/rage#353.
> age: Take recipients by reference in `Encryptor::with_recipients`

- age/CHANGELOG.md
- age/src/lib.rs
- age/src/simple.rs
> age: Add streamlined APIs for encryption and decryption
