- .github/workflows/interop.yml
- Cargo.lock
- Cargo.toml
- src/keys.rs
- src/protocol.rs
See https://groups.google.com/d/msg/age-dev/UAjkvLoCr9I/l4Q1h3OPAgAJ for details.
> Switch to Bech32 for age pubkey and secret key encodings

- src/format.rs
- src/format/scrypt.rs
- src/format/ssh_ed25519.rs
- src/format/ssh_rsa.rs
- src/format/x25519.rs
> Remove line_ending argument from format parsers

- CHANGELOG.md
- src/bin/rage-mount/main.rs
- src/bin/rage/error.rs
- src/bin/rage/main.rs
- src/error.rs
- src/format/scrypt.rs
- src/lib.rs
- src/protocol.rs
> Make max work factor for passphrases configurable

- age-core/CHANGELOG.md
- age-core/src/format.rs
- age/CHANGELOG.md
- fuzz/Cargo.lock
- fuzz/Cargo.toml
- fuzz/fuzz_targets/age_stanza.rs
> Fuzz age stanza

- .github/workflows/interop.yml
This should enable us to reproduce any failure.
Closes #72.
> Actions: Upload artifacts for failing interop test cases

- .github/workflows/audit.yml
> Actions: Add workflow that runs cargo-audit daily

- Cargo.lock
- age-core/Cargo.toml
- age/Cargo.toml
- fuzz/Cargo.lock
Closes https://github.com/str4d/rage/issues/69.
> Upgrade cookie-factory to 0.3.1

- age/CHANGELOG.md
- age/src/keys.rs
> Handle CRLFs when parsing secret keys

- HomebrewFormula/rage.rb
- README.md
> Add Homebrew formula

- Cargo.lock
- age/Cargo.toml
- age/src/cli_common.rs
- rage/CHANGELOG.md
- rage/src/bin/rage/error.rs
- rage/src/bin/rage/main.rs
> Unix: Allow piping input when decrypting with passphrase

- .github/workflows/ci.yml
- age/src/format/scrypt.rs
Currently this is just WASM targets except wasm32-wasi.
> Guess scrypt work factor for targets where SystemTime::now() panics

- age/src/primitives/stream.rs
It takes up an extra 4 bytes in memory, which is negligible as we only store one nonce per `STREAM`.
> Refactor STREAM nonce using u128

- age/src/primitives/armor.rs
- age/src/primitives/stream.rs
- age/src/protocol.rs
- age/src/protocol/decryptor.rs
Preparation for asynchronous decryption.
> Reader refactor

- age/CHANGELOG.md
- age/src/lib.rs
- age/src/primitives.rs
- age/src/primitives/armor.rs
- age/src/primitives/stream.rs
- age/src/protocol.rs
- age/src/protocol/decryptor.rs
- rage/src/bin/rage-mount/main.rs
- rage/src/bin/rage-mount/tar.rs
- rage/src/bin/rage-mount/zip.rs
- rage/src/bin/rage/main.rs
> Move ASCII armoring into an explicit API

- age/CHANGELOG.md
- age/src/format.rs
- age/src/primitives/stream.rs
- age/src/protocol.rs
This enables asynchronous encryption to the binary format.
> Encryptor::wrap_async_output

- age/CHANGELOG.md
- age/src/cli_common.rs
- age/src/keys.rs
- age/src/lib.rs
- age/src/openssh.rs
- age/src/protocol.rs
- age/src/ssh.rs
- age/src/ssh/identity.rs
- age/src/ssh/recipient.rs
- rage/src/bin/rage-mount/main.rs
- rage/src/bin/rage/error.rs
- rage/src/bin/rage/main.rs
This gets most of the way towards the desired refactor. The format-related logic will be refactored after introducing the new traits.
> SSH support refactor

- Cargo.lock
- age/Cargo.toml
- age/src/primitives/armor.rs
> impl AsyncWrite for ArmoredWriter

- rage/examples/generate-docs.rs
> fix URL example in manual

- Cargo.lock
- age-core/Cargo.toml
- age-core/src/primitives.rs
- age/Cargo.toml
- age/src/primitives/stream.rs
- fuzz-afl/Cargo.lock
- fuzz/Cargo.lock
We can finally bring in the speedup from here: https://github.com/str4d/rage/issues/57#issuecomment-605535052
> More crate updates

- .github/workflows/release.yml
I need to merge this PR in order to check that it works, and then uncomment the upload step once that's done.
Part #93.
> Actions: Enable manually testing the release workflow

- .github/workflows/interop.yml
This ensures that interop failures are reported back to FiloSottile/age.
> Actions: Always run status updates for triggered interop

- age/src/primitives/armor.rs
The `base64` crate internally processes 4 blocks of 8 bytes at a time. Previously we were only processing 48 bytes at a time, which was only creating a single iteration of base64's fast loop. We now process up to 8KiB at a time.
This also removes a transient buffer allocation per armor line, due to replacing `base64::encode_config` with `base64::encode_config_slice`.
> age: Encode armor in 8kiB chunks

- age-core/src/plugin.rs
- age-plugin/CHANGELOG.md
- age-plugin/Cargo.toml
- age-plugin/README.md
- age-plugin/README.tpl
- age-plugin/src/lib.rs
- age/CHANGELOG.md
- rage/CHANGELOG.md
- rage/Cargo.toml
- rage/src/bin/rage/error.rs
- rage/src/bin/rage/main.rs
> Move plugin support into beta

- age/CHANGELOG.md
- age/Cargo.toml
- age/src/identity.rs
- age/src/ssh/identity.rs
- age/src/util.rs
- age/tests/test_vectors.rs
> age: Re-enable age test vectors on Windows

- age/Cargo.toml
- age/README.md
- age/src/scrypt.rs
> age: Add support for using web performance timer to calculate scrypt work factor

- Cargo.lock
- age/CHANGELOG.md
- age/src/i18n.rs
> age: Ensure that the fallback language is always loaded

- rage/src/bin/rage-mount/main.rs
We disabled logging by default, so FUSE errors were not being shown.
Fixes str4d/rage#189.
> Return mount_fs errors from rage-mount instead of logging

- age/CHANGELOG.md
- age/src/lib.rs
- age/src/protocol.rs
- age/src/protocol/decryptor.rs
- age/tests/test_vectors.rs
- rage/src/bin/rage/main.rs
This makes decrypting multiple files with the same identities easier.
Fixes str4d/rage#212.
> age: Change RecipientsDecryptor to take an iterator of &'a dyn Identity

- Cargo.lock
- age-core/Cargo.toml
- age-core/src/primitives.rs
- age/Cargo.toml
- age/src/primitives/stream.rs
- fuzz-afl/Cargo.lock
- fuzz/Cargo.lock
> `chacha20poly1305 0.9`

- README.md
- age/README.md
Also updates format specification paragraph to match FiloSottile/age.
> Add age logo to READMEs

- Cargo.lock
- age/CHANGELOG.md
- age/Cargo.toml
- age/src/cli_common/file_io.rs
- rage/CHANGELOG.md
- rage/src/bin/rage-keygen/main.rs
- rage/src/bin/rage/main.rs
> Defer writing to stdout if we are reading from TTY

- Cargo.lock
- age-core/CHANGELOG.md
- age-core/src/plugin.rs
- age-plugin/CHANGELOG.md
- age-plugin/Cargo.toml
- age-plugin/src/identity.rs
- age-plugin/src/lib.rs
- age-plugin/src/recipient.rs
- age/CHANGELOG.md
- age/src/cli_common.rs
- age/src/encrypted.rs
- age/src/lib.rs
- age/src/plugin.rs
> Implement `confirm` plugin command

- age/CHANGELOG.md
- age/i18n/en-US/age.ftl
- age/i18n/es-AR/age.ftl
- age/i18n/it/age.ftl
- age/i18n/zh-CN/age.ftl
- age/i18n/zh-TW/age.ftl
- age/src/ssh.rs
- age/src/ssh/identity.rs
- age/src/ssh/recipient.rs
- rage/src/bin/rage/main.rs
> Detect and report unsupported SSH key types

- .github/workflows/release.yml
- rage/Cargo.toml
> Build musl Debian packages in addition to glibc

- age-plugin/examples/age-plugin-unencrypted.rs
> age-plugin: Add explosion triggers to the example plugin

- age/CHANGELOG.md
- age/i18n/en-US/age.ftl
- age/src/encrypted.rs
- age/src/identity.rs
- age/src/lib.rs
- age/src/plugin.rs
- rage/CHANGELOG.md
This is an alternative client-side fix to https://github.com/str4d/age-plugin-yubikey/issues/45, which is more forgiving of small delays by the user.
> Display a message if a plugin is slow to wrap or unwrap

- age/CHANGELOG.md
- age/benches/parser.rs
- age/src/encrypted.rs
- age/src/identity.rs
- age/src/protocol.rs
- rage/src/bin/rage/main.rs
> Fix codebase to allow Encryptor to implement Send

- age-plugin/CHANGELOG.md
- age-plugin/examples/age-plugin-unencrypted.rs
- age-plugin/src/lib.rs
> age-plugin: Make arguments to `run_state_machine` optional

- Cargo.lock
- age/Cargo.toml
- age/src/cli_common/file_io.rs
- supply-chain/config.toml
- supply-chain/imports.lock
> age: Replace `atty` with `is-terminal`

- age/src/primitives/armor.rs
This should make it more likely that users realise that they need to call `ArmoredWriter::finish` after finishing the encryptor.
Closes str4d/rage#412.
> age: Add examples to `ArmoredReader` and `ArmoredWriter`

- age/CHANGELOG.md
- age/src/cli_common.rs
- age/src/i18n.rs
- rage/i18n/en-US/rage.ftl
- rage/i18n/es-AR/rage.ftl
- rage/i18n/it/rage.ftl
- rage/i18n/zh-CN/rage.ftl
- rage/i18n/zh-TW/rage.ftl
- rage/src/bin/rage/error.rs
- rage/src/bin/rage/main.rs
- rage/tests/cmd/rage/decrypt-missing-identities-file.toml
> Deduplicate identity file parsing

- README.md
> rage: Add MacPorts package to installation list
